// Run against `npm start`. Uses the Codex bundled Playwright when available.
const path = require('node:path');
let playwright;
try { playwright = require(process.env.PLAYWRIGHT_MODULE || 'playwright'); }
catch { playwright = require(path.join(process.env.USERPROFILE || process.env.HOME, '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')); }
const { chromium } = playwright;
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' });
  await page.getByRole('heading', { name: '오늘, 어디로 떠나볼까요?' }).waitFor();
  fs.mkdirSync('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  await page.getByRole('button', { name: '조건 변경', exact: true }).click();
  await page.locator('select[name=region]').selectOption('연남');
  await page.locator('select[name=environment]').selectOption('실내');
  await page.locator('input[name=budget]').fill('20000');
  await page.getByRole('button', { name: '이 조건으로 코스 찾기' }).click();
  await page.locator('dialog').waitFor({ state: 'hidden' });
  assert.ok((await page.locator('.course-body').innerText()).includes('연남'));
  await page.getByRole('button', { name: '코스 저장', exact: true }).click();
  await page.getByRole('button', { name: '저장한 코스' }).click();
  assert.equal(await page.locator('.saved-grid .course-card').count(), 1);
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByRole('button', { name: '저장한 코스' }).click();
  assert.equal(await page.locator('.saved-grid .course-card').count(), 1);
  await page.getByRole('button', { name: '탐색', exact: true }).click();
  await page.getByRole('button', { name: 'AI와 계획하기', exact: true }).click();
  await page.getByRole('textbox', { name: '데이트 요청 메시지' }).fill('연남에서 실내로 1인 3만원');
  await page.getByRole('button', { name: '메시지 보내기' }).click();
  await page.locator('.chat-route').waitFor();
  assert.ok((await page.locator('.chat-route').innerText()).includes('연남'));
  await page.getByRole('button', { name: '이 코스를 지도에서 보기' }).click();
  await page.getByRole('searchbox').fill('존재하지않는곳');
  await page.getByText('검색 결과가 없어요. 검색어나 분류를 바꿔 주세요.').waitFor();
  await page.getByRole('searchbox').fill('');
  await page.getByRole('button', { name: '우리의 코스 자세히 보기' }).click();
  await page.locator('.timeline').waitFor();
  await page.locator('.stop-place').first().click();
  await page.getByRole('heading', { name: '장소 자세히 보기' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '로그인 · 회원가입' }).click();
  await page.getByRole('button', { name: '취향 프로필 만들기' }).click();
  await page.locator('input[name=name]').fill('민지');
  await page.locator('select[name=mbti]').selectOption('INFP');
  await page.getByLabel('전시', { exact: true }).check();
  await page.getByRole('button', { name: '다음으로', exact: true }).click();
  await page.getByRole('button', { name: '지역 직접 선택', exact: true }).click();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '마이페이지', exact: true }).click();
  assert.ok((await page.locator('.profile-info').innerText()).includes('INFP'));
  await page.getByRole('button', { name: '탐색', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#toast.show').waitFor({ state: 'hidden' });
  await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile must not overflow');
  const chips = await page.locator('.map-chips').boundingBox();
  const pin = await page.locator('.pin-button:not(.alternative)').first().boundingBox();
  assert.ok(pin.y > chips.y + chips.height, 'first map pin must clear the category filter');
  await page.getByRole('button', { name: 'AI와 계획하기', exact: true }).click();
  await page.screenshot({ path: 'artifacts/mobile-chat.png', fullPage: true });
  assert.ok(await page.locator('#chat-input').isVisible());
  assert.deepEqual(errors, []);
  console.log('PASS: desktop/mobile, constraints, save/reload, chat, search, detail, onboarding and overflow');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
